<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AccessLogWorker-e81f2d2b-efdf-415a-bead-7881d44f30c7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\classfiles\Application\Application.csproj" />
    <ProjectReference Include="..\classfiles\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Messaging.Shared\Messaging.Shared.csproj" />
  </ItemGroup>
</Project>
